### PR TITLE
Added Perl / Catalyst

### PR DESCRIPTION
**Pull request by moltar**
Added Perl / Catalyst

### CODE REVIEW

**Comment by moredip** [comment]
Thanks for the contribution, but it doesn't appear to be passing tests at the moment: https://www.todobackend.com/specs/index.html?https://todo-backend-catalyst.herokuapp.com/

From a quick look it seems that the server is returning 403 Forbidden in response to an OPTIONS request (part of the browser's CORS preflight check).

**Comment by moltar** [comment]
Oops, you are right. I was working on it more after submitting the PR and I probably broke it. Fixed now.

**Comment by moredip** [comment]
looks good. Thanks!

**Comment by moltar** [comment]
When will it show up on the front end?

**Comment by moredip** [comment]
It's deploying now, should be live in the next few minutes.

**Pull request merged**
