### PR TITLE
Added Swift/Kitura/Cassandra implementation

### PR DESCRIPTION
**Pull request by jesspittman**
.

### CODE REVIEW

**Comment by moredip** [comment]
Thanks for the submission Jessica. Unfortunately some of the tests are failing because your API implementation is returning `http://` scheme urls when the request comes in via an `https://` endpoint. This causes Mixed Content CORS failures in some browsers (e.g. Chrome).

Here's an example of the issue:

```
⋙ curl https://todolist-cassandra.mybluemix.net/
[
  {
    "id": "D2354C02-5AFB-4FF1-AD5A-CDFFD33A287B",
    "completed": false,
    "title": "blah",
    "user": "default",
    "url": "http://todolist-cassandra.mybluemix.net/api/todos/D2354C02-5AFB-4FF1-AD5A-CDFFD33A287B",
    "order": 10
  },
  {
    "id": "EFBBE553-46F4-4093-955D-CC6E56E20BC5",
    "completed": false,
    "title": "blah",
    "user": "default",
    "url": "http://todolist-cassandra.mybluemix.net/api/todos/EFBBE553-46F4-4093-955D-CC6E56E20BC5",
    "order": 523
  },
  {
    "id": "A98F28EE-3030-412C-9E99-20794F2D5A26",
    "completed": false,
    "title": "a todo",
    "user": "default",
    "url": "http://todolist-cassandra.mybluemix.net/api/todos/A98F28EE-3030-412C-9E99-20794F2D5A26",
    "order": 0
  },
  {
    "id": "C06D25CA-29AE-4283-9114-B7F62E6D7E40",
    "completed": false,
    "title": "blah",
    "user": "default",
    "url": "http://todolist-cassandra.mybluemix.net/api/todos/C06D25CA-29AE-4283-9114-B7F62E6D7E40",
    "order": 10
  },
  {
    "id": "0C243775-76BA-4909-87D4-19B16A845585",
    "completed": false,
    "title": "blah",
    "user": "default",
    "url": "http://todolist-cassandra.mybluemix.net/api/todos/0C243775-76BA-4909-87D4-19B16A845585",
    "order": 0
  }
]
```

**Comment by jesspittman** [comment]
It should be fixed now. Forgot to reenable https.

**Comment by moredip** [comment]
Thanks, looks good. 

Any chance you could add a Cassandra logo too?

**Comment by rfdickerson** [comment]
Hi, @moredip - we noticed that the link didn't show up on todobackend.com. Has @jesspittman sent you a Cassandra logo?

**Pull request merged**
