### PR TITLE
Update implementations.yaml

### PR DESCRIPTION
**Pull request by lutsen**
Added the Lagan implementation.

### CODE REVIEW

**Comment by moredip** [comment]
Thanks! Any chance you could also send a PR adding a Lagan logo to `source/images/logos`?

**Comment by moredip** [comment]
Oops, never mind. I see you already did.

**Comment by moredip** [comment]
@lutsen I noticed that your live implementation only supports CORS requests from http://www.todobackend.com, not https://www.todobackend.com. [(see here)](https://github.com/lutsen/lagan-todobackend/blob/master/routes/todobackend.php#L37).

This means that running the tests from http [works](http://www.todobackend.com/specs/index.html?https://www.laganphp.com/todobackend/todo), but from https [does not](https://www.todobackend.com/specs/index.html?https://www.laganphp.com/todobackend/todo). Could you fix that?

**Comment by lutsen** [comment]
@moredip Thanx, it is fixed now.

**Pull request merged**
