### PR TITLE
Proposed PHP with symfony 4 + api-platform

### PR DESCRIPTION
**Pull request by olberger**
Here's my proposed version with Symfony 4 and api-platform

### CODE REVIEW

**Comment by moredip** [comment]
Hi @olberger the specs aren't passing for your live implementation:

http://todobackend.com/specs/index.html?https://still-ravine-70063.herokuapp.com/

image

**Comment by olberger** [comment]
@moredip thx for caring... strange... It used to work when I asked for the pull request... did the specs evolve ?

**Comment by moredip** [comment]
No, specs haven’t changed for a long time.

**Comment by olberger** [comment]
Hi.

I've finally taken the time to check what's wrong. It appears that it works on http://www.todobackend.com/specs/index.html?https://still-ravine-70063.herokuapp.com/todos instead...

Would you reconsider my submission ?

**Pull request closed without merging**
