### PR TITLE
Add Azure Functions implementation

### PR DESCRIPTION
**Pull request by markheath**
Azure functions implementation with functions written using C#, F# and JavaScript and storing todos in Azure Table Storage

### CODE REVIEW

**Comment by moredip** [comment]
Thanks for the contribution. Unfortunately [the tests](https://www.todobackend.com/specs/index.html?https://functodobackend.azurewebsites.net/api/todos) seem to be failing due to issues with the pre-flight CORS OPTIONS request:



⋙ curl -vvv 'https://functodobackend.azurewebsites.net/api/todos' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: https://www.todobackend.com' -H 'Accept: */*' -H 'Referer: https://www.todobackend.com/specs/index.html?https://functodobackend.azurewebsites.net/api/todos' -H 'Access-Control-Request-Headers: content-type'
*   Trying 23.100.50.51...
* Connected to functodobackend.azurewebsites.net (23.100.50.51) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.azurewebsites.net
* Server certificate: Microsoft IT SSL SHA2
* Server certificate: Baltimore CyberTrust Root
> OPTIONS /api/todos HTTP/1.1
> Host: functodobackend.azurewebsites.net
> User-Agent: curl/7.43.0
> Access-Control-Request-Method: GET
> Origin: https://www.todobackend.com
> Accept: */*
> Referer: https://www.todobackend.com/specs/index.html?https://functodobackend.azurewebsites.net/api/todos
> Access-Control-Request-Headers: content-type
> 
< HTTP/1.1 400 Bad Request
< Content-Length: 11
< Content-Type: text/html
< Server: Microsoft-IIS/8.0
< X-Powered-By: ASP.NET
< Date: Wed, 22 Feb 2017 23:00:28 GMT
< 
* Connection #0 to host functodobackend.azurewebsites.net left intact
Bad Request

**Comment by markheath** [comment]
OK, that's strange. I've been running them successfully all day from todobackend.com and I have the CORS rules set up. Looks like Azure Functions just upgraded to a new version so maybe something is temporary broken. Apologies for inconveniencing you and I'll report back here once it's working again

**Comment by markheath** [comment]
ah, I've worked it out. I had entries for http://todobackend.com and  http://www.todobackend.com but not for https://

I've added the new CORS rules and the tests work at the endpoint you link to. The first method can sometimes take 20 seconds to respond if the function app is having a cold start.

**Comment by moredip** [comment]
Nice catch - everything looks good now. This http vs https thing happens quite frequently - I should probably add a hint to the implementation page. 

Thanks for the implementation! Interesting to see MS's serverless play. Also congrats on having what I think is the first multi-language implementation 😀

**Comment by markheath** [comment]
Great, and thank you for creating this site. It's a super helpful way to get a quick feel for lots of different back-end technologies, and the built-in spec runner is a really nice touch.

**Pull request merged**
