### PR TITLE
Add grape implementation

### PR DESCRIPTION
**Pull request by brianstorti**

### CODE REVIEW

**Comment by moredip** [comment]
Awesome, was hoping for a Grape example!

**Comment by brianstorti** [comment]
Cool :)
Is there anything else I need to do to get this merged?

**Comment by moredip** [comment]
No I just need to find a moment to review and then do a deploy.

Feel free to keep bugging me until that happens! :)

**Comment by brianstorti** [comment]
I didn't have the chance! Thanks.

**Pull request merged**
