### PR TITLE
Update implementations.yaml

### PR DESCRIPTION
**Pull request by rfdickerson**
Added an open source Swift implementation that can be run on Linux or Mac OS X, and deployed to servers using Cloud Foundry, Docker, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/todobackend/todo-backend-site/73)

### CODE REVIEW

**Comment by rfdickerson** [comment]
We might be the first Swift implementation listed on this site. There are other Swift frameworks that do similar things like [Vapor](https://github.com/qutheory/vapor), [Zewo](https://github.com/Zewo) that might join as well eventually.

**Comment by moredip** [comment]
Very excited to have a Swift implementation!

**Comment by moredip** [comment]
@rfdickerson, any chance you could also send a PR to add logos for Swift and Kituru?

**Comment by rfdickerson** [comment]
Absolutely! I created a PR for the images here: https://github.com/TodoBackend/todo-backend-site/pull/74. btw, had some trouble getting `bundle install` to work on the site code, otherwise I would have added the links directly to it.

**Comment by moredip** [comment]
Can you share any details on what trouble you had with bundle install? I want to make the contribution process as frictionless as possible. If theres a rough edge with running locally I'd love to smooth it out.

**Pull request merged**
