### PR TITLE
Add OCaml implementation

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by moredip** [comment]
Great to see an OCaml implementation! 

I'm very reluctant to include listing which don't have a live instance running somewhere. All the implementations listed today do that. 

Would you be able to put a running instance of this implementation somewhere? Heroku is a popular choice for other contributors, and I'm guessing there's an OCaml buildpack you could take advantage of.

**Comment by raboof** [comment]
It's running at the live_url http://todo-backend-ocaml.bzzt.net:3000/todos (http://www.todobackend.com/client/index.html?http://todo-backend-ocaml.bzzt.net:3000/todos and http://www.todobackend.com/specs/index.html?http://todo-backend-ocaml.bzzt.net:3000/todos should work). 

This is currently on Amazon EC2, I might move it in the future but I'll be sure to send a PR when that's done.

**Comment by moredip** [comment]
Ah, great. In that case could you just update the live_url field in implementations.yaml to point to that url?

**Comment by raboof** [comment]
Ah, sorry, missed that!

**Comment by moredip** [comment]
:+1:  Should be live in a few mins. Thanks again for providing an OCaml example.

**Pull request merged**
