### PR TITLE
added an example with ASP.NET and Couchbase

### PR DESCRIPTION
**Pull request by mgroves**

### CODE REVIEW

**Comment by moredip** [comment]
Thanks for the contribution. Unfortunately, I ran into some problems while running the specs - looks like the server running your implementation was maybe down, or slow? 

image

You might want to consider deploying your implementation to a service like Heroku - that's a popular choice for TodoBackend implementors.

**Comment by mgroves** [comment]
I tried to save a few bucks and deploy Couchbase to a way lower-spec machine than is recommend on SpinUp. I will try to redeploy today on a beefier machine, and I will leave a comment here to let you know that it's ready to be checked again, if that's okay?

**Comment by mgroves** [comment]
I just deployed to Azure, please check at your convenience. Thank you!

**Comment by mgroves** [comment]
I realize this may not be the highest priority issue in anyone's life right now, but it is still ready to review when you get a chance @moredip :)

**Pull request merged**
