### PR TITLE
added Azure SQL implementation

### PR DESCRIPTION
**Pull request by yorek**
backend API with Node.js / Azure Functions / Azure SQL

### CODE REVIEW

**Comment by yorek** [comment]
any news for this PR?

**Comment by moredip** [comment]
Hi @yorek thanks for checking in. Apologies that it takes me a while to review these, but it is on my radar. Will hopefully get to it soon.

**Comment by yorek** [comment]
Sure, thanks!

**Comment by yorek** [comment]
Pinging again :)

**Comment by moredip** [comment]
Thanks for the nudge, and sorry for the delay. Your contribution is merged, and the site is redeploying now. Your entry should be live in the next few minutes.

**Pull request merged**
